### ISSUE TITLE
Segfault (nullptr) access in interface claim

### ISSUE THREAD

**Issue by diggit** [MiSo1289/usb-asio#1]
Hi,
first of all, thank you for all your work... díky :)

I am trying to use your asio wrapper of libusb and I am struggling a little bit. It's all blowing up in interface claiming. There is uninitialized data access resulting in null pointer de-reference. 

My code is just slightly modified example from readme.

Constructing interface object calls [`claim`](https://github.com/MiSo1289/usb-asio/blob/master/include/usb_asio/usb_interface.hpp#L115).

`claim` itself calls [`unclaim`](https://github.com/MiSo1289/usb-asio/blob/master/include/usb_asio/usb_interface.hpp#L121) at first.

`unclaim` calls [`::libusb_release_interface`](https://github.com/MiSo1289/usb-asio/blob/master/include/usb_asio/usb_interface.hpp#L164) which takes device handler as argument.

Device handle pointer is obtained by calling [`device_handle`](https://github.com/MiSo1289/usb-asio/blob/master/include/usb_asio/usb_interface.hpp#L238), which returns `device_handle_`, but this data member is not set yet. That happens [at the end of `claim` fcn](https://github.com/MiSo1289/usb-asio/blob/master/include/usb_asio/usb_interface.hpp#L138).

Unless I am using it wrong, there is several ways to fix this:
- `device_handle_` has to be set before calling `unclaim`
- there has to be overload of interface `unclaim` which accepts device handle directly (available in claim fcn).
- avoid calling `unclaim` when `device_handle_` is not valid

**Comment by MiSo1289** [comment]
Hi, thanks for the report; `unclaim()` should be a no-op if handle is not set, but it looks like `is_claimed()` returns the wrong thing:

```c++
        [[nodiscard]] auto is_claimed() const noexcept -> bool
        {
            return device_handle_ == nullptr;
        }
 ```
 
 Should be `!= nullptr`, will fix.
 
 I planned to use this library for a project which I had to abandon, so there are definitely bugs in basic features like this; I might get to use it for another project in not-so-distant future though :) feel free to report other problems / submit PRs if you find other issues.

**Comment by diggit** [comment]
> Should be `!= nullptr`, will fix.

Oh, I totally missed that. Thanks for quick fix!

**Comment by diggit** [comment]
I believe, this is not fully fixed yet, as `basic_usb_interface::device_handle_` is missing initialization and thus `is_claimed()` may incorrectly return because `device_handle_` holds some garbage.
